name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - run: python -m pip install --upgrade pip
      - run: pip install ruff mypy pytest pytest-cov
      - run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - run: pip install ruff mypy pytest pytest-cov httpx pytest-asyncio
      - run: pip install -r requirements.txt
      - run: pytest --cov=src --cov-report=xml --cov-report=term
      - run: ruff check .
      - run: mypy .
      - run: pytest --cov=src -q
